Backup1/KitundaChurch/Models/Event.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace KitundaChurch.Models
{
    public class Event
    {
        public Event()
        {
         
            timer = DateTime.Now;
        }
        public int Id { get; set; }
     
        [Display(Name ="DateTime")]
        public DateTime timer { get; set; }

        [Display(Name = "Title")]
        [DisplayFormat(DataFormatString = "{0:hh:mm:ss tt}", ApplyFormatInEditMode = true)]
        public string Title { get; set; }
        [Display(Name = " more explanation")]
        [DataType(DataType.MultilineText)]
        public string contentual { get; set; }
        public string place { get; set; }
        public virtual/* ICollection< */UserImageFile Image { get; internal set; }
        //public virtual UserImageFile image { get; set; }
    }
}

Backup1/KitundaChurch/Controllers/EventsController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using KitundaChurch.Models;
using System;
using System.Collections.Generic;
using System.IO;
using Microsoft.AspNetCore.Http;
using System.Threading.Tasks;
using MoreLinq;

namespace KitundaChurch.Controllers
{
    public class EventsController : Controller
    {
        private readonly KitundaChurchContext _context;

        public EventsController(KitundaChurchContext context)
        {
            _context = context;
        }

        // GET: Events
        public ActionResult Index()
        {
            var list = _context.Events.Include(m=>m.Image).Where(n => n.timer >= DateTime.Now).ToList();
            var item = list.MinBy(b=>b.timer).SingleOrDefault();
            ViewBag.tot = item.timer;
            ViewBag.litle = item.Title;
            ViewBag.desc = item.contentual;
            ViewBag.image = "data:image/jpg;base64," + Convert.ToBase64String(item.Image.content, 0, item.Image.content.Length);
            ViewBag.mahal = item.place;
            return PartialView(list);
        }

        // GET: Events/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Event @event = _context.Events.Find(id);
            if (@event == null)
            {
                return NotFound();
            }
            return View(@event);
        }
        //[OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult ViewSavedImage( )
        {
            //UserImageFile file = new UserImageFile();
            return PartialView("ViewSavedImage"/* file*/);
        }
        // GET: Events/Create
        [HttpGet]
        public ActionResult CreateAsync()
        {
           
            //Get the full file path which we will use to save the file.

            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateAsync( Event @event, List<IFormFile> Upload)  
        {
            if (ModelState.IsValid)
            {
              

                    _context.Add(@event);
                    await _context.SaveChangesAsync();
                await RegimAsync(@event, Upload);
                return RedirectToAction("Index");

            }

               
            
                return View(@event);
        }
        public async Task RegimAsync(Event eve, List<IFormFile> Upload)
        {
            
            foreach (var a in Upload)
            {
                UserImageFile fil = new UserImageFile();
                fil.FileName = a.FileName;
                fil.ContentType = a.ContentType;
                using (var memorystream = new MemoryStream())
                {
                    a.CopyTo(memorystream);
                    fil.content = memorystream.ToArray();

                }
                fil.EventId=eve.Id;
                     _context.Add(fil);
                await _context.SaveChangesAsync();
            }
        }
        // GET: Events/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return  NotFound();
            }
            Event @event = _context.Events.Find(id);
            if (@event == null)
            {
                return NotFound();
            }
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind("Id,image,timer,contentual")] Event @event)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(@event).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(@event);
        }

        // GET: Events/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return  NotFound();
            }
            Event @event = _context.Events.Find(id);
            if (@event == null)
            {
                return NotFound();
            }
            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Event @event = _context.Events.Find(id);
            _context.Events.Remove(@event);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Backup1/KitundaChurch/Views/Events/CreateAsync.cshtml
@model KitundaChurch.Models.Event

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("CreateAsync", "Events", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Event</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       <div class="form-group">
        <div class="col-md-2"></div>
         <div class="col-md-10">

               <img src="" Class="imgDisplay img-responsive  img-thumbnail"  style="position:relative; background-color:lightgray;margin-bottom:15px;width:350px; height:250px; "/>
           
          
          <input type="file" name="Upload" id="Upload"  onchange="ShowPreview(this)" class="btn btn-default btn-file" >
           
           </div></div>
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
    @Html.LabelFor(model => model.timer, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.timer, new { htmlAttributes = new { @class = "form-control glyphicon glyphicon-calendar" } })
        @Html.ValidationMessageFor(model => model.timer, "", new { @class = "text-danger" })
    </div>
</div>
        <div class="form-group">
            @Html.LabelFor(model => model.place, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.place, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.place, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contentual, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.contentual, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.contentual, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
        
@section Scripts {
   

<script type="text/javascript">
               function ShowPreview(input) {
                   if (input.files && input.files[0]) {
                       var ImageDir = new FileReader();
                       ImageDir.onload = function (e) {
                           $('.imgDisplay').attr('src', e.target.result);
                       }
                     ImageDir.readAsDataURL(input.files[0]);
                   }
               }
              

               
             
    $(function () { // will trigger when the document is ready
        $('.datepicker').datetimepicker(

            ); //Initialise any date pickers
    });

</script>
}

Backup1/KitundaChurch/Views/Events/Delete.cshtml
@model KitundaChurch.Models.Event

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.timer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.timer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.contentual)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.contentual)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Backup1/KitundaChurch/Views/Events/Details.cshtml
@model  KitundaChurch.Models.Event

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.timer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.timer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.contentual)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.contentual)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Backup1/KitundaChurch/Views/Events/Edit.cshtml
@model KitundaChurch.Models.Event

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Event</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        @*<div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.timer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.timer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.timer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contentual, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.contentual, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.contentual, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
   
}

Backup1/KitundaChurch/Views/Events/Index.cshtml
@model IEnumerable<KitundaChurch.Models.Event>

@{
    ViewBag.Title = "Index";
}


<p>
    @Html.ActionLink("Create New", "CreateAsync")

</p>
<div class="Events" style="height:auto; width:100%">
    <div class="col-md-6" matukio>
        <div class="col-md-12" style="background-color:rgba(128, 128, 128, 0.12);  padding-left:0; padding-right:0;">
           <div class="imig" style="height:300px; width:auto; position:relative;">
                @if (ViewBag.image != null)
                {
                    <hr />
                    <img style="width:100%; height:inherit; " src="@ViewBag.image">
                }
            <span id="soon">Next Coming Soon</span></div>
          <div class="row" style="margin-left: 8px;">
            <div class="col-md-3 p col-xs-1" style="box-shadow:0 0 0 2px rgba(11, 180, 236, 0.95), 0 0 0 2px rgba(23, 124, 224, 0.97);"><span  id="days"></span><p>Days</p></div>
              <div class="col-md-3 p col-xs-1" > <span id="hours"></span><p>Hours</p></div>
                  <div class="col-md-3 p col-xs-1" ><span id="mins"></span><p>Minutes</p></div>
                  <div class="col-md-3 p col-xs-1" ><span id="secs"></span><p>Seconds</p></div>
             
            </div>
           <div style="height:auto; width:100%; margin-left:5px;">
               <h3>
                  @ViewBag.litle
               </h3>
               <p id="muda"></p>
               <p>at @ViewBag.mahal</p>
           </div>
        
  
    </div></div>
    @foreach (var item in Model)
    {
        <div>
<div class="col-md-2 boxed" >
    <h2 style="margin: 0px 2px 0px 2px;" id="box"></h2>
    <p style="margin: 0px 2px 0px 2px;" id="mon"></p>
    <p style="margin: 0px 2px 0px 2px;" id="yea"></p>
</div>
        <div class="col-md-4 soon">

            <h5 class="TheTitle" style="color:rgba(23, 124, 224, 0.97); margin:0; padding:0;">  @Html.DisplayFor(modelItem => item.Title)</h5>
            <hr>
           
            <p>
                @Html.DisplayFor(modelItem => item.timer)
               
            </p>
         
        </div>
       </div>


    } 
    </div>
@*@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/jquery")*@
    <script>
        var b=new Date("@ViewBag.tot");
        var countDownDate =b.getTime();

        // Update the count down every 1 second
        var x = setInterval(function () {

            // Get todays date and time
            var now = new Date().getTime();

            // Find the distance between now an the count down date
            var distance = countDownDate - now;

            // Time calculations for days, hours, minutes and seconds
            var days = Math.floor(distance / (1000 * 60 * 60 * 24));
            var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
            var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
            var seconds = Math.floor((distance % (1000 * 60)) / 1000);

            // Display the result in the element with id="demo"
            document.getElementById("days").innerHTML = days;

            document.getElementById("hours").innerHTML = hours;
            document.getElementById("mins").innerHTML = minutes;
            document.getElementById("secs").innerHTML = seconds;

            // If the count down is finished, write some text
            if (distance < 0) {
                clearInterval(x);
                document.getElementById("demo").innerHTML = "EXPIRED";
            }
        }, 1000);
        document.getElementById("muda").innerHTML = "On " + b;
       
        document.getElementById("box").innerHTML = b.getDate();
        document.getElementById("mon").innerHTML = b.getUTCMonth();
        document.getElementById("yea").innerHTML = b.getYear();
        //dayName will return the name of day
        </script>
    
    