Backup1/KitundaChurch/Models/Matoleo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace KitundaChurch.Models
{
    public class Matoleo
    {
        public int MatoleoId { get; set; }
        [Display(Name = "Jumla")]
        [Required]
        public int Total { get; set; } = 0;
        [Display(Name = "Tarehe")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Savetime { get; set; } =DateTime.Now;

        public double Zaka { get; set; } = 0;
        [Display(Name = "Conf")]
        public double sadakaConf { get; set; } = 0;
        [Display(Name = "Bk ")]
        public double sadakaBk { get; set; } = 0;
        [Display(Name = "Majengo ")]
        public double sadakaMajengo { get; set; } = 0;
        [Display(Name = "Makambi")]
        public double sadakaMakambi { get; set; } = 0;

        [Display(Name = "Mpango")]
        public double MpangoKanisa { get; set; } = 0;
        public virtual ChurchMembers ChurchMembers { get; set; }
        public virtual  int ChurchMembersId { get; set; }
        public  ICollection<Mengineyo> mengineyo { get; set; }

    }

   
}

Backup1/KitundaChurch/Controllers/MatoleosController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KitundaChurch.Models;
using System.Collections.Generic;
using Rotativa.AspNetCore;
using System;

namespace KitundaChurch.Controllers
{

    public class MatoleosController : Controller
    {
        public int PageSize { get; set; } = 4;

        //const string SessionKeyDate = "_Date";
        private readonly KitundaChurchContext _context;

        public MatoleosController(KitundaChurchContext context)
        {
            _context = context;
        }

        // GET: Matoleos
        public IActionResult Index()

        {
            Matoleo matoleo = new Matoleo();

            var listed = _context.Matoleo.Include(m => m.ChurchMembers).Include(m => m.mengineyo).GroupBy(x => x.Savetime).First().ToList();


            ViewBag.Mengineyo = listed.Select(n=>n.mengineyo).ToList();
            ViewBag.sum1 = listed.Sum(n => n.sadakaBk);
            ViewBag.sum2 = listed.Sum(n => n.sadakaConf);
            ViewBag.sum3 = listed.Sum(n => n.Zaka);
            ViewBag.sum4 = listed.Sum(n => n.Total);
            ViewBag.sum5 = listed.Sum(n => n.MpangoKanisa);
            ViewBag.sum6 = listed.Sum(n => n.sadakaMakambi);
            ViewBag.sum7 = listed.Sum(n => n.sadakaMajengo);

            return View(listed);
        }

        [HttpPost]
        public IActionResult Index(Matoleo matoleo)
        {
            var listed = _context.Matoleo.Include(m => m.ChurchMembers).Include(n => n.mengineyo).Where(n => n.Savetime == matoleo.Savetime).ToList();
            ViewBag.sum1 = listed.Sum(n => n.sadakaBk);
            ViewBag.sum2 = listed.Sum(n => n.sadakaConf);
            ViewBag.sum3 = listed.Sum(n => n.Zaka);
            ViewBag.sum4 = listed.Sum(n => n.Total);
            ViewBag.sum5 = listed.Sum(n => n.MpangoKanisa);
            ViewBag.sum6 = listed.Sum(n => n.sadakaMakambi);
            ViewBag.sum7 = listed.Sum(n => n.sadakaMajengo);
            ViewBag.mengineyo = listed.Select(n => n.mengineyo).ToList();
            return View(listed);
        }
        // GET: Matoleos/Details/5
        public async Task<IActionResult> DetailsAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var matoleo = await _context.Matoleo
                .Include(m => m.ChurchMembers)
                .SingleOrDefaultAsync(m => m.MatoleoId == id);
            if (matoleo == null)
            {
                return NotFound();
            }

            return View(matoleo);
        }
        //[HttpGet]
        //public IActionResult GetUser()
        //{

        //    return PartialView();
        //}
        //[HttpPost]

        public JsonResult GetUser(string Name)
        {



            var members = (from n in _context.ChurchMembers
                           where n.Name.StartsWith(Name)
                           select n.Name);

            //var Name = members.Name;


            return new JsonResult(members);

        }
        public async Task<IActionResult> RegMemberAsync(string searchString)
        {
            ChurchMembers members = new ChurchMembers();
            members.Name = searchString;
            if (ModelState.IsValid)
            {
                _context.Add(members.Name);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return PartialView();
        }
        [HttpGet]
        // GET: Matoleos/Create
        public IActionResult Create()
        {
            Matoleo matoleo = new Matoleo();
            //ViewData["Savetime"] = SessionKeyDate;


            return View(matoleo);
        }

        // POST: Matoleos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAsync(Matoleo matoleo, IList<Mengineyo> mengineyo)
        {
            //HttpContext.Session.Set<DateTime>(SessionKeyDate, matoleo.Savetime);

            //var meng = formCollectiom.Contains("Name")
            if (ModelState.IsValid)
            {
                var exists = _context.Matoleo.Include(v => v.ChurchMembers).AsNoTracking().Any(x => x.ChurchMembers.Name == matoleo.ChurchMembers.Name);
                if (exists)
                {
                    _context.Update(matoleo);

                }

                _context.Add(matoleo);
                await _context.SaveChangesAsync();
                await NudiaAsync(matoleo, mengineyo);

                return RedirectToAction(nameof(Index));
            }
            ViewData["ChurchMembersId"] = new SelectList(_context.ChurchMembers, "ChurchMembersId", "ChurchMembersId", matoleo.ChurchMembersId);
            return View(matoleo);
        }

        public async Task NudiaAsync(Matoleo matoleo, IList<Mengineyo> mengineyo)
        {
            foreach (var m in mengineyo)
            {

                Mengineyo mengi = new Mengineyo()
                {
                    descr = m.descr,
                    Amount = m.Amount
                };
                mengi.MatoleoId = matoleo.MatoleoId;
                _context.Add(mengi);
                await _context.SaveChangesAsync();
            }
        }
        [HttpGet]
        // GET: Matoleos/Edit/5
        public async Task<IActionResult> EditAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var matoleo = await _context.Matoleo.Include(n => n.ChurchMembers).SingleAsync(m => m.MatoleoId == id);
            if (matoleo == null)
            {
                return NotFound();
            }
            ViewData["ChurchMembersId"] = new SelectList(_context.ChurchMembers, "ChurchMembersId", "ChurchMembersId", matoleo.ChurchMembersId);
            ViewData["MatoleoId"] = new SelectList(_context.Matoleo, "MatoleoId", "MatoleoId", matoleo.MatoleoId);
            return View(matoleo);
        }

        // POST: Matoleos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditAsync(int id, Matoleo matoleo)
        {
            if (id != matoleo.MatoleoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(matoleo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MatoleoExists(matoleo.MatoleoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ChurchMembersId"] = new SelectList(_context.ChurchMembers, "ChurchMembersId", "ChurchMembersId", matoleo.ChurchMembersId);
            ViewData["MatoleoId"] = new SelectList(_context.Matoleo, "MatoleoId", "MatoleoId", matoleo.MatoleoId);
            return View(matoleo);
        }

        public IActionResult SummaryAsync(Matoleo matoleo,  int Page = 1)
        {
            
            var listed = _context.Matoleo.AsNoTracking().Where(n=>n.Savetime==matoleo.Savetime).Include(b => b.ChurchMembers);


            //.Skip((productPage - 1) * PageSize)
            //.Take(PageSize);
            var vai = ReflectionIT.Mvc.Paging.PaginList<Matoleo>.CreateAsync(listed, PageSize, Page, matoleo.Savetime.ToString(), matoleo.Savetime.ToString());
            vai.RouteValue = new Microsoft.AspNetCore.Routing.RouteValueDictionary
            {
                {matoleo.Savetime.ToString() , matoleo.Savetime}
            };
            ViewBag.sum1 = vai.Sum(n => n.sadakaBk);
            ViewBag.sum2 = vai.Sum(n => n.sadakaConf);
            ViewBag.sum3 = vai.Sum(n => n.Zaka);
            ViewBag.sum4 = vai.Sum(n => n.Total);
            ViewBag.sum5 = vai.Sum(n => n.MpangoKanisa);
            ViewBag.sum6 = vai.Sum(n => n.sadakaMakambi);
            ViewBag.sum7 = vai.Sum(n => n.sadakaMajengo);
            return View(vai);
        }

        // GET: Matoleos/Delete/5
        public async Task<IActionResult> DeleteAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var matoleo = await _context.Matoleo
                .Include(m => m.ChurchMembers)
                .SingleOrDefaultAsync(m => m.MatoleoId == id);
            if (matoleo == null)
            {
                return NotFound();
            }

            return View(matoleo);
        }

        // POST: Matoleos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmedAsync(Matoleo mato)
        {
            var matoleo = await _context.Matoleo.SingleOrDefaultAsync(m => m.MatoleoId ==mato.MatoleoId);
            _context.Matoleo.Remove(matoleo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MatoleoExists(int id)
        {
            return _context.Matoleo.Any(e => e.MatoleoId == id);
        }



        //public static class SessionExtensions
        //{
        //    public static void Set<T>(this ISession session, string key, T value)
        //    {

Backup1/KitundaChurch/Views/Matoleos/Create.cshtml
@model KitundaChurch.Models.Matoleo

@{
    ViewData["Title"] = "Create";
}
<h4>Matoleo</h4>
<hr/>

 
    <div class="col-md-4">
        @*<div class="formPartial">
            @{ await Html.RenderPartialAsync("GetUser"); }
        </div>*@
     
        
            <div class="row">

                <form asp-controller="Matoleos" asp-action="CreateAsync" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    @*<input asp-for="ChurchMembersId" class="form-control hidden" />*@
                    <div class="form-group col-lg-offset-6">
                        <label asp-for="Savetime" class="control-label"></label>
                        <input asp-for="Savetime" class="form-control datepicker" />
                        <span asp-validation-for="Savetime" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ChurchMembers.Name" class="control-label"></label>
                        <input asp-for="ChurchMembers.Name" class="form-control" />
                        <span asp-validation-for="ChurchMembers.Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Total" class="control-label"></label>
                        <input asp-for="Total" class="form-control" />
                        <span asp-validation-for="Total" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Zaka" class="control-label"></label>
                        <input type="checkbox" id="Zaka1">
                        <input asp-for="Zaka" class="form-control" />
                        <span asp-validation-for="Zaka" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label>  Sadaka<input type="checkbox" id="Sadaka"></label>
                        <div class="sadaka">
                            <div class="form-group col-md-4">
                                <span> <label class="control-label" >Sadaka Ya Pamoja</label></span>
                                <input class="form-control" type="text"  id="sadakayapamoja" name="sadakayapamoja" value="0" />
                                
                            </div>

                            <div class="form-group col-md-4">
                                <span> <label asp-for="sadakaConf" class="control-label"></label></span>
                                <input asp-for="sadakaConf" class="form-control" />
                                <span asp-validation-for="sadakaConf" class="text-danger"></span>
                            </div>
                            <div class="form-group col-md-4">
                                <span><label asp-for="sadakaBk" class="control-label"></label></span>
                                <input asp-for="sadakaBk" class="form-control" />
                                <span asp-validation-for="sadakaBk" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="sadakaMajengo" class="control-label"></label>
                        <input asp-for="sadakaMajengo" class="form-control" />
                        <span asp-validation-for="sadakaMajengo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="sadakaMakambi" class="control-label"></label>
                        <input asp-for="sadakaMakambi" class="form-control" />
                        <span asp-validation-for="sadakaMakambi" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="MpangoKanisa" class="control-label"></label>
                        <input asp-for="MpangoKanisa" class="form-control" />
                        <span asp-validation-for="MpangoKanisa" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="col-md-6">Mengineyo: </label>
                        <input type="button" @*style="margin:17px 0px 0px 7px" *@ class="btnPlus col-md-pull-2 btn btn-default" value="+" />
                    </div>

                    <div class="form-group">
                        <table id="table1">
                            @*<tr>
                                <td>
                                    Desc:
                                    <input type="text" class="form-control" asp-for="mengineyo.descr" />
                                </td>
                                <td>
                                    Amount:
                                    <input type="text" class="form-control" asp-for="mengineyo.Amount" value="0" />
                                </td>

                                <td>
                                    <input type="button" style="margin:17px 0px 0px 15px" class="btnminus  form-control" value="-" />
                                </td>
                            </tr>*@
                        </table>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </form>
            </div>
        </div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section scripts {
    @*@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}*@
    <script>

        $(document).ready(function () {



            function calc(b = 0) {



                $("#Zaka1").change(function () {

                    var t = $("#Total").val();
                    var jum = t - b;

                    
                    if (this.checked) {

                        $("#Zaka").val(jum / 2);
                        $("#sadakayapamoja").val(jum / 2);
                        $("#sadakaConf").val((jum / 2) * 0.58);
                        $("#sadakaBk").val((jum / 2) * 0.42);
                    }


                });

                var g=
                    $("#Sadaka").change(function () {
                        var t = $("#sadakayapamoja").val();

                        $("#sadakaConf").val((t ) * 0.58);
                        $("#sadakaBk").val((t ) * 0.42);
                    
                });
                
            }
            $("#sadakaMakambi").val(0);
            $("#sadakaMajengo").val(0);
            $("#MpangoKanisa").val(0);
            //$('#savetime').val(Date(4/28/2018));
            calc();
            var id = 0;
            function addRow() {

                var html = '<tr>' +
                    '<td>Desc:<input type="text" class="form-control" data-val="true" data-val-required="The Description is required." id="mengineyo[' + id + ']_descr" name="mengineyo[' + id + '].descr"  /> </td>' +
                    '<td> Amount:<input type="text" class="form-control" data-val="true" data-val-required="The Amount is required." id="mengineyo[' + id + ']_Amount" name="mengineyo[' + id + '].Amount"  /></td>' +
                    '<td><input type="button" style="margin:17px 0px 0px 7px" class="btnminus form-control" value="-" /></td>' +
                    '</tr>';
                $(html).appendTo($("#table1"));
                id++;
            };
             //$("#sadakaMajengo").change(function () {
             //    var b = $(this).val();
             //    $("#Zaka1").val(this.checked);
             //    calc(b);
             //});
             //$("#sadakaMakambi").change(function () {

             //    var b = $(this).val();

             //    calc(b).$("Zaka1").change();
             //});

             //$("#MpangoKanisa").change(function () {
             //    var b = $(this).val();
                
             //    calc(b);
             //});


            $(".btnPlus").click(addRow);

            $(document).on("click", ".btnminus", function () {
                $(this).closest('tr').remove();

            });

       
              /*  $(function () {
                    $('#datepicker').datetimepicker();
            });*/



        
            //$("#bton").click(function () {
                
            //    $(".row").show();
            //    $("#bton").hide();  
            //});
    });
    </script>
}

Backup1/KitundaChurch/Views/Matoleos/DeleteAsync.cshtml
@model KitundaChurch.Models.Matoleo

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Matoleo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ChurchMembers.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ChurchMembers.Name)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.Zaka)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Zaka)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.sadakaConf)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.sadakaConf)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.sadakaBk)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.sadakaBk)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.sadakaMajengo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.sadakaMajengo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.sadakaMakambi)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.sadakaMakambi)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MpangoKanisa)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MpangoKanisa)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Savetime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Savetime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>
       
    </dl>
    
    <form  method="post" asp-action="Delete">
        <input type="hidden" asp-for="MatoleoId" />
    
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Backup1/KitundaChurch/Views/Matoleos/EditAsync.cshtml
@model KitundaChurch.Models.Matoleo

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Matoleo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Matoleos"  asp-action="EditAsync" method="Post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ChurchMembersId" />
            <input type="hidden" asp-for="MatoleoId" />
            <div class="form-group">
                <label asp-for="ChurchMembers.Name" class="control-label"></label>
                <input asp-for="ChurchMembers.Name" class="form-control">
                <span asp-validation-for="ChurchMembers.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Zaka" class="control-label"></label>
                <input asp-for="Zaka" class="form-control" />
                <span asp-validation-for="Zaka" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="sadakaConf" class="control-label"></label>
                <input asp-for="sadakaConf" class="form-control" />
                <span asp-validation-for="sadakaConf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="sadakaBk" class="control-label"></label>
                <input asp-for="sadakaBk" class="form-control" />
                <span asp-validation-for="sadakaBk" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="sadakaMajengo" class="control-label"></label>
                <input asp-for="sadakaMajengo" class="form-control" />
                <span asp-validation-for="sadakaMajengo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="sadakaMakambi" class="control-label"></label>
                <input asp-for="sadakaMakambi" class="form-control" />
                <span asp-validation-for="sadakaMakambi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MpangoKanisa" class="control-label"></label>
                <input asp-for="MpangoKanisa" class="form-control" />
                <span asp-validation-for="MpangoKanisa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Savetime" class="control-label"></label>
                <input asp-for="Savetime" class="form-control" />
                <span asp-validation-for="Savetime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Backup1/KitundaChurch/Views/Matoleos/GetUser.cshtml
@model KitundaChurch.Models.ChurchMembers
@{
    ViewData["Title"] = "GetUser";
}
<script>

     $(document).ready(function () {
         $("#Name").autocomplete({
             source: function (request, response) {
                 $.ajax({
                     url: "/Matoleos/GetUser",
                     beforeSend: function (xhr) {
                         xhr.setRequestHeader("XSRF-TOKEN",
                             $('input:hidden[name="__RequestVerificationToken"]').val());
                     },
                     type: "POST",
                     dataType: "json",
                     data: { Name: request.term },
                     success: function (data) {
                         response($.map(data, function (item) {
                             return { label: item.Name, value: item.Name };
                         }))

                     }
                 })
             },
             messages: {
                 noResults: "", results: ""
             }
         });
     })

     function myshow() {

         $(".row").show();
         $("#bton").hide();
         $("#matoleo_churchmembersid").val()
     }

            //$("#bton").click(function () {

            //    $(".row").show();
            //    $("#bton").hide();
            //});
</script>

<form id="GetUser" method="post">

    <h2>Get Mtoaji</h2>

    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <div class="majib"></div>
    </div>
        
        <div class="form-group">
            <input type="submit" id="search" value="Search" class="btn btn-default" />
        </div>
</form>


    <script src="~/lib/jquery/dist/jquery.js"></script>
       

Backup1/KitundaChurch/Views/Matoleos/Report.cshtml
@{
    ViewData["Title"] = "Report";
}
<div class="text-center">
<h2>KANISA LA WAADVENTISTA WA SABATO</h2>
<h3>KANDA YA MASHARIKI MWA TANZANIA</H3>
<h4>TAARIFA YA FEDHA MWEZI...............</h4>
    </div>
@*<div><a class="col-md-offset-10 btn btn-success" href="@Url.Action("PrintViewToPdf","Matoleos")">Export To PDF</a>
    
    </div>*@
@*<form asp-controller="Matoleos" asp-action="Report" method="post">
  
   <div class="">
    <div class="form-group col-md-6">
        <label  class="control-label">From</label>
        <input name="Savetime1" id="savetime1" class="form-control datepicker" />
       
    </div>
    <div class="form-group col-md-6">
        <label  class="control-label">To</label>
        <input name="Savetime1" id="savetime1" class="form-control datepicker" />
       
    </div></div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-default" />*@
    @*</div>
    </form>*@
<table style="margin:20px;" border="1">
<thead>
    A: MATOLEO YA KANISA MAHALIA YALIYOPELEKWA KONFERENSI
</thead>
    <tbody>

<tr>
    <th>Tarehe</th>
@foreach (var a in ViewBag.tar)
{
    <th>@a</th>
}
  <th>Jumla</th>
</tr>
    <tr>
        <td>Zaka</td>
      @foreach (var a in ViewBag.SumZaka)
      {
        <td class="@a">@a</td>
      }
        <td>@ViewBag.SumZakaf</td>
    </tr>
    <tr>
        <td>Sadaka Konferensi 58%</td>
        @foreach (var a in ViewBag.SumConf)
        {
            <td class="@a">@a</td>
        }
        <td>@ViewBag.Conff</td>
    </tr>
    <tr>
        <td>Sadaka Makambi</td>
        @foreach (var a in ViewBag.SumMbi)
        {
          
            <td class="@a">@a</td>

        }
        <td>@ViewBag.SumMbif</td>
       
    <tr>
        <td>Jumla A</td>
        @foreach (var a in ViewBag.A)
        {

        <td>@a</td>
        }
        <td>@(ViewBag.SumZakaf+ViewBag.Conff+ViewBag.SumMbif)</td>
    </tr>
        </tbody>

</table>

<table style="margin:20px;" border="1">
    <thead>
        B: MATOLEO YALIYOBAKI KANISANI
    </thead>
    <tbody>
        <tr>
            <th>Tarehe</th>
            @foreach (var a in ViewBag.tar)
            {
                <th>@a</th>
            }
            <th>Jumla</th>
        </tr>
        <tr>
            <td>Sadaka ya pamoja 42%</td>
            @foreach (var a in ViewBag.SumBk)
            {
                <td class="@a">@a</td>
            }
            <td>@ViewBag.SumBkf</td>
        </tr>
        <tr>
            <td>Sadaka Ujenzi Makambi</td>
            @foreach (var a in ViewBag.SumNgo)
            {
                <td class="@a">@a</td>
            }
            <td>@ViewBag.SumNgof</td>
        </tr>

        <tr>
            <td>Jumla B</td>
              @foreach (var a in ViewBag.B)
              {

                <td>@a</td>
              }
               <td>@(ViewBag.SumBkf+ ViewBag.SumNgof)</td>
            </tr>
        <tr>
            <th>Jumla A+B</th>
            @foreach (var a in ViewBag.SumTotal)
            {
                <th>@a</th>
            }
            <th>@ViewBag.SumTotalf</th>
        </tr>
    </tbody>

</table >
<table style="margin:20px;" border="1">
    <thead>
        C: FEDHA ZILIZOPELEKWA BENKI
    </thead>
    <tbody>
        

        <tr>
            <td>Tarehe</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        

        <tr>
            <td>KONFERENCE</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>KANISA MAHALIA</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
       <tr>
            <td>Jumla </td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </tbody>

</table>
@section scripts {
    <script>
        $(document).ready(function ()
        {



        });


    </script>



}