Backup1/KitundaChurch/Models/News.cs
using System;
using System.Collections.Generic;

namespace KitundaChurch.Models
{
    public class News
    {
        public int Id { get; set; }
       
        public string content { get; set; }
        public string Title { get; set; }
        public int CategoryId { get; set; }
        public IList<Category> category { get; set; }
        public byte images { get; set; }
        public DateTime? time { get; set; }
        

    }

    public class Category
    {
        public int CategoryId { get; set; }
        public string CName { get; set; }
    }
}

Backup1/KitundaChurch/Controllers/NewsController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using KitundaChurch.Models;
using System;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace KitundaChurchControllers
{
    public class NewsController : Controller
    {
      
            private readonly KitundaChurchContext _context;

            public NewsController(KitundaChurchContext context)
            {
                _context = context;
            }
            // GET: News
            public ActionResult Index()
        {  
           
            return View( _context.News.ToList());
        }

        // GET: News/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            News news = _context.News.Find(id);
            if (news == null)
            {
                return NotFound();
            }
            return View(news);
        }

        // GET: News/Create
        [HttpGet]
        public ActionResult Create( )
        {
            ViewBag.Listed = new SelectList(_context.Category.Select(n=>n.CName).ToList());
           News news = new News();
            news.time = DateTime.Now;
            return View(news);
        }

        // POST: News/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
       
        public ActionResult Create([Bind("Id,CategoryId, content,Title,time")] News news)
        {
            if (ModelState.IsValid)
            {
                
                _context.News.Add(news);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(news);
        }

        // GET: News/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id != null)
            {
                return NotFound();
            }
            News news = _context.News.Find(id);
            if (news != null)
            {
                return NotFound();
            }
            return View(news);
        }

        // POST: News/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind("Id,content,Title,images,time")] News news)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(news).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(news);
        }

        // GET: News/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            News news = _context.News.Find(id);
            if (news == null)
            {
                return NotFound();
            }
            return View(news);
        }

        // POST: News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            News news = _context.News.Find(id);
            _context.News.Remove(news);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Backup1/KitundaChurch/Views/Shared/Components/News/Default.cshtml
@model IEnumerable<KitundaChurch.Models.News>
<style>
    .soon {
        overflow: hidden !important;
        color: inherit !important;
    }

        .soon img {
            width: 200px !important;
            height: auto !important;
            border: 8px ridge darkgray !important;
            float: left !important;
            -webkit-transition: all 1s ease !important; /* Safari and Chrome */
            -moz-transition: all 1s ease !important; /* Firefox */
            -ms-transition: all 1s ease !important; /* IE 9 */
            -o-transition: all 1s ease !important; /* Opera */
            transition: all 1s ease !important;
        }

            .soon img:hover {
                -webkit-transform: scale(1.25) !important; /* Safari and Chrome */
                -moz-transform: scale(1.25) !important; /* Firefox */
                -ms-transform: scale(1.25) !important; /* IE 9 */
                -o-transform: scale(1.25) !important; /* Opera */
                transform: scale(1.25) !important;
            }
</style>








@foreach (var item in Model)
{
    <div>
        @*<div class="col-md-2 boxed">

                    @if (ViewBag.image != null)
                {
                        <hr />
                        <img style="width:100%; height:inherit; " src="@ViewBag.image">
                    }
                    <span id="soon">Next Coming Soon</span>

            </div>*@
        <a href=" @Url.Action("Details","News",  new { id = item.Id })" class="col-md-12 soon ">

             <h5 class="TheTitle" style="color:rgba(23, 124, 224, 0.97); margin:0; padding:0;">  @Html.DisplayFor(modelItem => item.Title)</h5>
            @Html.Raw(item.content)
            <hr />


            <p>
                @Html.DisplayFor(modelItem => item.time)

            </p>

        </a>
    </div>
        
        <hr>

}

@*@section script
    {
        <script>
            //$(document).ready(function () {
            //    $('.soon').closest('img').css("");
            //})

        </script>
    }*@